[build]
  command = "npm rebuild lightningcss && npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_BLOBS_ENABLED = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
