[build]
  command = "npm install lightningcss-linux-x64-gnu@1.29.0 --save-dev --ignore-scripts && npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_BLOBS_ENABLED = "false"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
